### ISSUE TITLE
Problems getting graphite-api running on Centos/Apache

### ISSUE THREAD

**Issue by swissdave** [brutasse/graphite-api#106]
Hi there,

I've followed the instructions and tried to get graphite-api running on a Centos 6.2 system with Apache 2.2.  I created the graphite-api.yaml:

```
search_index: cd index
finders:
  - graphite_api.finders.whisper.WhisperFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
whisper:
  directories:
    - /opt/graphite/storage/whisper
time_zone: UTC
```

Created the WSGI script:

```
[root@centosvm wsgi-scripts]# pwd; ls -la
/var/www/wsgi-scripts
total 12
drwxr-xr-x  2 root root 4096 Apr  6 17:41 .
drwxr-xr-x. 7 root root 4096 Apr  6 17:40 ..
-rwxr-xr-x  1 root root   48 Apr  6 17:41 graphite-api.wsgi
[root@centosvm wsgi-scripts]# cat graphite-api.wsgi 
from graphite_api.app import app as application
```

Using the default vhost config from the docs.

httpd logfile looks like:

```
[Mon Apr 06 18:39:50 2015] [warn] module wsgi_module is already loaded, skipping
[Mon Apr 06 18:39:50 2015] [notice] Digest: generating secret for digest authentication ...
[Mon Apr 06 18:39:50 2015] [notice] Digest: done
[Mon Apr 06 18:39:50 2015] [notice] Apache/2.2.15 (Unix) DAV/2 Phusion_Passenger/3.0.19 mod_wsgi/3.2 Python/2.6.6 PHP/5.3.3 configured -- resuming normal operations
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22228): Target WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi' cannot be loaded as Python module.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22228): Exception occurred processing WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi'.
[Mon Apr 06 18:39:50 2015] [error] Traceback (most recent call last):
[Mon Apr 06 18:39:50 2015] [error]   File "/var/www/wsgi-scripts/graphite-api.wsgi", line 1, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from graphite_api.app import app as application
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/graphite_api-1.0.1-py2.6.egg/graphite_api/app.py", line 14, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import get_logger
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/__init__.py", line 42, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import twisted
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/twisted.py", line 152, in <module>
[Mon Apr 06 18:39:50 2015] [error]     class PlainFileLogObserver(object):
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib64/python2.6/site-packages/zope/interface/declarations.py", line 495, in __call__
[Mon Apr 06 18:39:50 2015] [error]     raise TypeError("Can't use implementer with classes.  Use one of "
[Mon Apr 06 18:39:50 2015] [error] TypeError: Can't use implementer with classes.  Use one of the class-declaration functions instead.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22229): Target WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi' cannot be loaded as Python module.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22229): Exception occurred processing WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi'.
[Mon Apr 06 18:39:50 2015] [error] Traceback (most recent call last):
[Mon Apr 06 18:39:50 2015] [error]   File "/var/www/wsgi-scripts/graphite-api.wsgi", line 1, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from graphite_api.app import app as application
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/graphite_api-1.0.1-py2.6.egg/graphite_api/app.py", line 14, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import get_logger
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/__init__.py", line 42, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import twisted
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/twisted.py", line 152, in <module>
[Mon Apr 06 18:39:50 2015] [error]     class PlainFileLogObserver(object):
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib64/python2.6/site-packages/zope/interface/declarations.py", line 495, in __call__
[Mon Apr 06 18:39:50 2015] [error]     raise TypeError("Can't use implementer with classes.  Use one of "
[Mon Apr 06 18:39:50 2015] [error] TypeError: Can't use implementer with classes.  Use one of the class-declaration functions instead.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22225): Target WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi' cannot be loaded as Python module.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22225): Exception occurred processing WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi'.
[Mon Apr 06 18:39:50 2015] [error] Traceback (most recent call last):
[Mon Apr 06 18:39:50 2015] [error]   File "/var/www/wsgi-scripts/graphite-api.wsgi", line 1, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from graphite_api.app import app as application
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/graphite_api-1.0.1-py2.6.egg/graphite_api/app.py", line 14, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import get_logger
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/__init__.py", line 42, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import twisted
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/twisted.py", line 152, in <module>
[Mon Apr 06 18:39:50 2015] [error]     class PlainFileLogObserver(object):
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib64/python2.6/site-packages/zope/interface/declarations.py", line 495, in __call__
[Mon Apr 06 18:39:50 2015] [error]     raise TypeError("Can't use implementer with classes.  Use one of "
[Mon Apr 06 18:39:50 2015] [error] TypeError: Can't use implementer with classes.  Use one of the class-declaration functions instead.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22226): Target WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi' cannot be loaded as Python module.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22226): Exception occurred processing WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi'.
[Mon Apr 06 18:39:50 2015] [error] Traceback (most recent call last):
[Mon Apr 06 18:39:50 2015] [error]   File "/var/www/wsgi-scripts/graphite-api.wsgi", line 1, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from graphite_api.app import app as application
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/graphite_api-1.0.1-py2.6.egg/graphite_api/app.py", line 14, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import get_logger
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/__init__.py", line 42, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import twisted
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/twisted.py", line 152, in <module>
[Mon Apr 06 18:39:50 2015] [error]     class PlainFileLogObserver(object):
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib64/python2.6/site-packages/zope/interface/declarations.py", line 495, in __call__
[Mon Apr 06 18:39:50 2015] [error]     raise TypeError("Can't use implementer with classes.  Use one of "
[Mon Apr 06 18:39:50 2015] [error] TypeError: Can't use implementer with classes.  Use one of the class-declaration functions instead.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22227): Target WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi' cannot be loaded as Python module.
[Mon Apr 06 18:39:50 2015] [error] mod_wsgi (pid=22227): Exception occurred processing WSGI script '/var/www/wsgi-scripts/graphite-api.wsgi'.
[Mon Apr 06 18:39:50 2015] [error] Traceback (most recent call last):
[Mon Apr 06 18:39:50 2015] [error]   File "/var/www/wsgi-scripts/graphite-api.wsgi", line 1, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from graphite_api.app import app as application
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/graphite_api-1.0.1-py2.6.egg/graphite_api/app.py", line 14, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import get_logger
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/__init__.py", line 42, in <module>
[Mon Apr 06 18:39:50 2015] [error]     from structlog import twisted
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib/python2.6/site-packages/structlog-15.1.0-py2.6.egg/structlog/twisted.py", line 152, in <module>
[Mon Apr 06 18:39:50 2015] [error]     class PlainFileLogObserver(object):
[Mon Apr 06 18:39:50 2015] [error]   File "/usr/lib64/python2.6/site-packages/zope/interface/declarations.py", line 495, in __call__
[Mon Apr 06 18:39:50 2015] [error]     raise TypeError("Can't use implementer with classes.  Use one of "
[Mon Apr 06 18:39:50 2015] [error] TypeError: Can't use implementer with classes.  Use one of the class-declaration functions instead.
```

There's a working Graphite Web setup there, so mod_wsgi must be working in a basic sense..  Grateful for any pointers..

**Comment by winguru** [comment]
This looks like it may be an issue with the Python zope.interface package:
https://pypi.python.org/pypi/zope.interface/3.3.0.1#declaring-implemented-interfaces

I'm using a later version of this on a different platform and not getting this error.
Do you know what version you have installed?

Just a suggestion, but you may want to uninstall the RPM version and install via pip:
`pip install zope.interface`

**Comment by swissdave** [comment]
Will give it a try - thanks very much

**Comment by swissdave** [comment]
OK, I removed the python-zope-interface-3.5.2-2.1.el6.x86_64 package I had installed and installed it via pip as suggested - I now have version 4.1.2 and those errors have  gone.

I corrected the config, giving:
```
search_index: /var/graphite-api/index
finders:
  - graphite_api.finders.whisper.WhisperFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
whisper:
  directories:
    - /opt/graphite/storage/whisper
time_zone: UTC
```
`/var/graphite/api/index` is an empty 644 file owned by apache
`/opt/graphite/storage/whisper` is where my Graphite data is
The error log now looks like:
```
[Mon Apr 20 21:47:03 2015] [error] {"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
[Mon Apr 20 21:47:03 2015] [error] {"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
[Mon Apr 20 21:47:03 2015] [error] {"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
[Mon Apr 20 21:47:03 2015] [error] {"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
[Mon Apr 20 21:47:03 2015] [error] {"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "event": "reading index data"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "duration": 0.00077605247497558594, "total_entries": 0, "event": "search index reloaded"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "event": "reading index data"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "duration": 0.0007610321044921875, "total_entries": 0, "event": "search index reloaded"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "event": "reading index data"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "duration": 0.00017881393432617188, "total_entries": 0, "event": "search index reloaded"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "event": "reading index data"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "duration": 7.2956085205078125e-05, "total_entries": 0, "event": "search index reloaded"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "event": "reading index data"}
[Mon Apr 20 21:47:03 2015] [error] {"index_path": "/var/graphite-api/index", "duration": 5.1021575927734375e-05, "total_entries": 0, "event": "search index reloaded"}
```
and the access log:
```
::1 - - [20/Apr/2015:21:13:37 +0200] "POST /render HTTP/1.1" 400 65
::1 - - [20/Apr/2015:21:19:27 +0200] "POST /render HTTP/1.1" 400 65
```
Grafana shows a red exclamation mark and says the timeseries query failed.

**Comment by swissdave** [comment]
Trying ```http://centosvm.localdomain:8013/render?target=test``` worked OK.
```http://centosvm.localdomain:8013/render/?width=586&height=308&_salt=1429560181.264&target=carbon.agents.centosvm_localdomain-a.cpuUsage&from=-24minutes&format=json``` just returned "[]" though, and logged:
```
[Mon Apr 20 22:03:32 2015] [error] {"node": "<LeafNode[7f01fcc9fdd0]: carbon.agents.centosvm_localdomain-a.cpuUsage (<graphite_api.finders.whisper.WhisperReader object at 0x7f01fcca0690>)>", "start": 1429562372, "end": 1429563812, "event": "no results"}
```

**Comment by brutasse** [comment]
That looks good now. Graphite-api seems to work properly, although it doesn't find any data.

What does `http://centosvm.localdomain:8013/metrics/find?query=*` return you?

**Comment by swissdave** [comment]
Looks reasonable:
```
[{"text": "Test_Cluster", "expandable": 1, "leaf": 0, "id": "Test_Cluster", "allowChildren": 1}, {"text": "carbon", "expandable": 1, "leaf": 0, "id": "carbon", "allowChildren": 1}, {"text": "xxxx", "expandable": 1, "leaf": 0, "id": "xxxx", "allowChildren": 1}, {"text": "zzzz", "expandable": 1, "leaf": 0, "id": "zzzz", "allowChildren": 1}, {"text": "aaaaaa", "expandable": 1, "leaf": 0, "id": "aaaaaa", "allowChildren": 1}, {"text": "gmetad", "expandable": 1, "leaf": 0, "id": "gmetad", "allowChildren": 1}, {"text": "hist", "expandable": 1, "leaf": 0, "id": "hist", "allowChildren": 1}, {"text": "jvm", "expandable": 1, "leaf": 0, "id": "jvm", "allowChildren": 1}]
```

**Comment by brutasse** [comment]
Yes, that looks good. Are whisper files properly updated by carbon?

**Comment by swissdave** [comment]
Yes, the graphite-web setup works fine..

**Comment by swissdave** [comment]
Just got this running fine at work, so must have just been something strange with my graphite setup at home.  Thanks for the pointers.

**Comment by brutasse** [comment]
Ok, great!
