### ISSUE TITLE
Gunicorn worker failed to boot

### ISSUE THREAD

**Issue by feangulo** [brutasse/graphite-api#12]
I know Gunicorn is working properly because I tested it with another test app. However, when I point it to the graphite-api application, the workers fail to start up and I get no indication of why.

```
# python -V
Python 2.6.6
[root@ip graphite_api]# sudo gunicorn -w2 graphite_api.app:app
2014-03-31 23:29:28 [28346] [INFO] Starting gunicorn 18.0
2014-03-31 23:29:28 [28346] [INFO] Listening at: http://127.0.0.1:8000 (28346)
2014-03-31 23:29:28 [28346] [INFO] Using worker: sync
2014-03-31 23:29:28 [28351] [INFO] Booting worker with pid: 28351
2014-03-31 23:29:28 [28354] [INFO] Booting worker with pid: 28354
Traceback (most recent call last):
  File "/usr/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==18.0', 'console_scripts', 'gunicorn')()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/wsgiapp.py", line 71, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/lib/python2.6/site-packages/gunicorn/app/base.py", line 143, in run
    Arbiter(self).run()
  File "/usr/lib/python2.6/site-packages/gunicorn/arbiter.py", line 203, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/lib/python2.6/site-packages/gunicorn/arbiter.py", line 298, in halt
    self.stop()
  File "/usr/lib/python2.6/site-packages/gunicorn/arbiter.py", line 341, in stop
    self.reap_workers()
  File "/usr/lib/python2.6/site-packages/gunicorn/arbiter.py", line 452, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

**Comment by gr4y** [comment]
I know that issue is about one year old, but I just discovered that problem and don't know how to solve it. Me and python are not the best friends, tbh. 

OS: `Debian Wheezy`

My `/etc/graphite-api.yaml`, which is just copied from the docs and the `logging` part from here: 
```
search_index: /srv/graphite/index
finders:
  - graphite_api.finders.whisper.WhisperFinder
functions:
  - graphite_api.functions.SeriesFunctions
  - graphite_api.functions.PieFunctions
whisper:
  directories:
    - /srv/graphite/whisper
carbon:
  hosts:
    - 127.0.0.1:7002
  timeout: 1
  retry_delay: 15
  carbon_prefix: carbon
  replication_factor: 1

logging:
  version: 1
  disable_existing_loggers: true
  handlers:
    file:
      class: logging.FileHandler
      filename: /var/log/graphite-api.log
  loggers:
    graphite_api:
      handlers:
        - file
      propagate: true
      level: DEBUG
```

I run gunicorn with the following command as root:
`gunicorn --log-level debug --error-logfile=out --access-logfile=out graphite_api.app:app -b 0.0.0.0:8898`

which results in that:
```
[2015-05-11 13:27:14 +0000] [28678] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x215e7d0>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x215e500>
  pre_fork: <function pre_fork at 0x215e668>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: out
  group: 0
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: True
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x215e398>
  pre_exec: <function pre_exec at 0x215ecf8>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x215e938>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x2160410>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x215ee60>
  post_request: <function post_request at 0x215ef50>
  user: 0
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x215eaa0>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x2160140>
  chdir: /srv/graphite
  paste: None
  default_proc_name: graphite_api.app:app
  errorlog: out
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x215e230>
  worker_abort: <function worker_abort at 0x215eb90>
  bind: ['0.0.0.0:8898']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x21602a8>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix:
[2015-05-11 13:27:14 +0000] [28678] [INFO] Starting gunicorn 19.3.0
[2015-05-11 13:27:14 +0000] [28678] [DEBUG] Arbiter booted
[2015-05-11 13:27:14 +0000] [28678] [INFO] Listening at: http://0.0.0.0:8898 (28678)
[2015-05-11 13:27:14 +0000] [28678] [INFO] Using worker: sync
[2015-05-11 13:27:14 +0000] [28683] [INFO] Booting worker with pid: 28683
[2015-05-11 13:27:14 +0000] [28678] [DEBUG] 1 workers
[2015-05-11 13:27:15 +0000] [28678] [INFO] Shutting down: Master
[2015-05-11 13:27:15 +0000] [28678] [INFO] Reason: Worker failed to boot.
```

Output of `python --version`
```
Python 2.7.3
```

Output of `pip freeze`:
```
Flask==0.10.1
GnuPGInterface==0.3.2
Jinja2==2.7.2
MarkupSafe==0.18
MySQL-python==1.2.3
PIL==1.1.7
PyYAML==3.11
Pygments==1.5
Radicale==0.9
Rest==0.1
SOAPpy==0.12.0
Twisted==15.1.0
Werkzeug==0.10.4
argparse==1.2.1
boto==2.3.0
cairocffi==0.6
ceres==0.10.0
cffi==1.0.0b2
chardet==2.0.1
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
docutils==0.8.1
dropbox==2.0.0
duplicity==0.6.23
fpconst==0.7.2
graphite-api==1.0.1
gunicorn==19.3.0
itsdangerous==0.24
lockfile==0.8
lxml==2.3.2
mclogalyzer==1.0
paho-mqtt==1.0
paramiko==1.7.7.1
peewee==2.4.5
pycparser==2.12
pycrypto==2.6
pycryptopp==0.5.29
pyparsing==2.0.3
python-apt==0.8.8.2
python-dateutil==1.5
python-debian==0.1.21
python-debianbts==1.11
pytz==2015.2
pyzor==0.5.0
reportbug==6.4.4
six==1.9.0
structlog==15.1.0
txAMQP==0.6.2
urllib3==1.8.2
urwid==1.0.1
whisper==0.9.13
wsgiref==0.1.2
zope.interface==4.1.2
```

**Comment by gr4y** [comment]
So I found out what was the problem. I had created the directory `/srv/graphite/index` and when I started `graphite_api` with `uswgi` it just showed me an error message that `/srv/graphite/index` is a directory. After deleting that directory it worked with `uwsgi` and `gunicorn`.

It would have helped when gunicorn would show error messages like `uwsgi` does.
