### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by maguec** [brutasse/graphite-api#123]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api-1.0.1-py2.7.egg/graphite_api/middleware.py", line 46, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api-1.0.1-py2.7.egg/graphite_api/middleware.py", line 15, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api-1.0.1-py2.7.egg/graphite_api/app.py", line 153, in metrics_find
    key=lambda node: node.name
  File "/usr/local/lib/python2.7/dist-packages/graphite_api-1.0.1-py2.7.egg/graphite_api/storage.py", line 22, in find
    for node in finder.find_nodes(query):
  File "/usr/local/lib/python2.7/dist-packages/cyanite.py", line 104, in find_nodes
    if path['leaf']:
TypeError: string indices must be integers
```
When trying 
10.0.2.2 - - [28/Aug/2015 00:40:24] "GET /metrics/find/?query=* HTTP/1.1" 500 -

I see the following returned from the cyanite server localhost:8080 via tcpdump
```
GET /paths?query=%2A HTTP/1.1
Host: 172.18.12.18:8080
Accept-Encoding: gzip, deflate, compress
Accept: */*
User-Agent: python-requests/2.2.1 CPython/2.7.6 Linux/3.13.0-44-generic

HTTP/1.1 200 OK
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

246
["carbon.relays.cyanite-cb82790e.disconnects","carbon.relays.cyanite-cb82790e.dispatcher4.wallTime_us","collectd.vagrant-ubuntu-trusty-64.interface-eth0.if_errors.rx","carbon.relays.cyanite-cb82790e.dispatcher1.metricsReceived","carbon.relays.cyanite-cb82790e.dispatcher5.wallTime_us","carbon.relays.cyanite-cb82790e.metricsSent","carbon.relays.cyanite-cb82790e.dispatcher1.wallTime_us","carbon.relays.cyanite-cb82790e.server_wallTime_us","collectd.vagrant-ubuntu-trusty-64.df-tmp-vagrant-puppet-3-manifests.df_complex-free","carbon.relays.cyanite-cb82790e.dispatcher3.wallTime_us"]
0
```

**Comment by maguec** [comment]
if I look at the value of path being returned it is a string:

carbon.relays.cyanite-cb82790e.disconnects

**Comment by brutasse** [comment]
This is an issue with the latest Cyanite: https://github.com/pyr/cyanite/issues/119

Hopefully this will be fixed soon in Cyanite :)

**Comment by brutasse** [comment]
The issue has been fixed upstream. Cyanite master doesn't have this issue anymore.
