### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by chjohnst** [brutasse/graphite-api#137]
If I flick this to &from=-10mins in the URI I get this error, if I remove it I end up getting data served.  Did not dig into this much other then I see this traceback from time to time.  I am on graphite-api master (1.1) and graphite-cyanite (0.44 and 0.46 tested to see if it helps).  I can dif more tomorrow but curious if you see anything out of the ordinary. 

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 401, in render
    series_list = evaluateTarget(context, target, data_store)
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 496, in evaluateTarget
    result = evaluateTokens(requestContext, tokens, data_store)
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 514, in evaluateTokens
    arg, data_store) for arg in tokens.call.args]
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 514, in evaluateTokens
    arg, data_store) for arg in tokens.call.args]
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "/usr/lib/python2.6/site-packages/graphite_api/app.py", line 509, in evaluateTokens
    return data_store.get_series_list(tokens.pathExpression)
  File "/usr/lib/python2.6/site-packages/graphite_api/render/datalib.py", line 121, in get_series_list
    for data in self.data.get(path):
TypeError: 'NoneType' object is not iterable

**Comment by chjohnst** [comment]
Looks to be realted to the issue below, ill mark this closed as I have tested out the patch and it works correctly now. 

https://github.com/brutasse/graphite-api/issues/85
