### ISSUE TITLE
averageAbove() fails if there is no data

### ISSUE THREAD

**Issue by Glandos** [brutasse/graphite-api#146]
I'm not sure this is the root cause, but calling graphite-api with averageAbove on a series that have no data produce the following trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/monitoring/graphite-api/lib/python3.4/site-packages/graphite_api/app.py", line 401, in render
    series_list = evaluateTarget(context, target, data_store)
  File "/var/www/monitoring/graphite-api/lib/python3.4/site-packages/graphite_api/app.py", line 496, in evaluateTarget
    result = evaluateTokens(requestContext, tokens, data_store)
  File "/var/www/monitoring/graphite-api/lib/python3.4/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "/var/www/monitoring/graphite-api/lib/python3.4/site-packages/graphite_api/app.py", line 520, in evaluateTokens
    ret = func(requestContext, *args, **kwargs)
  File "/var/www/monitoring/graphite-api/lib/python3.4/site-packages/graphite_api/functions.py", line 1672, in averageAbove
    return [series for series in seriesList if safeAvg(series) >= n]
  File "/var/www/monitoring/graphite-api/lib/python3.4/site-packages/graphite_api/functions.py", line 1672, in 
    return [series for series in seriesList if safeAvg(series) >= n]
TypeError: unorderable types: NoneType() >= int()
```
Calling without any functions works as expected.

**Comment by Glandos** [comment]
Better later than never. Thanks a lot!
