### ISSUE TITLE
TypeError: movingAverage() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by JFC-MC** [brutasse/graphite-api#160]
Hello, we have graphite-api 1.1 and when we try to invoke movingAverage() with ANY number of arguments it complaints with:

```
curl https://10.100.1.20:7777/render?&target=movingAverage(0,10,0)
Traceback (most recent call last):
  File "/opt/bitnami/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/bitnami/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/bitnami/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/bitnami/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/bitnami/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/bitnami/python/lib/python2.7/site-packages/graphite_api/app.py", line 401, in render
    series_list = evaluateTarget(context, target, data_store)
  File "/opt/bitnami/python/lib/python2.7/site-packages/graphite_api/app.py", line 496, in evaluateTarget
    result = evaluateTokens(requestContext, tokens, data_store)
  File "/opt/bitnami/python/lib/python2.7/site-packages/graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "/opt/bitnami/python/lib/python2.7/site-packages/graphite_api/app.py", line 520, in evaluateTokens
    ret = func(requestContext, *args, **kwargs)
TypeError: movingAverage() takes exactly 3 arguments (1 given)
```

```
# pip list |grep -i graphite-api
graphite-api (1.1)
# python -V
Python 2.7.10
(it's Bitnami portable python)
```
Any ideas? (on another server we have the same issue)

**Comment by JFC-MC** [comment]
Worth to mention, at least these functions produce exactly the same error.
averageAbove
holtWintersForecast
holtWintersAberration
averageBelow

**Comment by brutasse** [comment]
Can you post the full output of `pip list`?

**Comment by JFC-MC** [comment]
boto (2.6.0)
cairocffi (0.7.2)
cffi (1.3.1)
Django (1.7.10)
docutils (0.10)
elementtree (1.2.7-20070827-preview)
Flask (0.10.1)
gevent (1.0.1)
graphite-api (1.1)
greenlet (0.4.3)
html5lib (0.90)
itsdangerous (0.24)
Jinja2 (2.8)
lxml (3.3.6)
Markdown (2.0.3)
MarkupSafe (0.15)
mercurial (2.1)
MySQL-python (1.2.3rc1)
pbr (0.10.0)
PIL (1.1.7)
Pillow (2.6.1)
pip (8.0.2)
psutil (0.6.1)
psycopg2 (2.6)
pycairo (1.8.4)
pycparser (2.14)
pycrypto (2.6.1)
pydot (1.0.28)
pyparsing (1.5.5)
pysqlite (2.6.3)
python-ldap (2.4.10)
python-Levenshtein (0.10.2)
python-memcached (1.45)
python-openid (2.2.5)
pytz (2015.7)
PyXML (0.8.4)
PyYAML (3.10)
reportlab (2.5)
setuptools (7.0)
simplejson (2.0.9)
six (1.7.3)
stevedore (1.1.0)
structlog (15.3.0)
Twisted (15.5.0)
txAMQP (0.6.2)
tzlocal (1.2)
virtualenv (1.11.6)
virtualenv-clone (0.2.5)
virtualenvwrapper (4.3.1)
Werkzeug (0.11.2)
whisper (0.9.13)
zope.interface (4.1.3)
ZSI (2.0)

**Comment by brutasse** [comment]
Thanks -- I suspect this is because of pyparsing.

Can you try upgrading it to a version `>=1.5.7`?

**Comment by JFC-MC** [comment]
Yes, it's working now successfully with pyparsing-2.1.0.
Thanks!

**Comment by brutasse** [comment]
Cool! :+1:
