### ISSUE TITLE
Permission denied on different metrics with same permissions

### ISSUE THREAD

**Issue by cflinspach** [brutasse/graphite-api#231]
I'm using graphite-api (1.1.3) on Ubuntu 16.04 LTS and we get a permission denied error on some metrics, but not others. All the metrics have the same permissions. 

Error when we go to http://render?format=json&target=keepLastValue(icinga2.host1.services.Ambient_Temperature.snmp_temp_check.perfdata.Temp.value,%205)&from=-7d&until=-6min :
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/app.py", line 375, in render
    data_store = fetchData(context, paths)
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/render/datalib.py", line 143, in fetchData
    for node in app.store.find(pathExpr, startTime, endTime):
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/storage.py", line 22, in find
    for node in finder.find_nodes(query):
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/finders/whisper.py", line 37, in find_nodes
    for absolute_path in self._find_paths(root_dir, pattern_parts):
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/finders/whisper.py", line 84, in _find_paths
    for match in self._find_paths(absolute_path, patterns):
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/finders/whisper.py", line 84, in _find_paths
    for match in self._find_paths(absolute_path, patterns):
  File "/usr/local/lib/python2.7/dist-packages/graphite_api/finders/whisper.py", line 74, in _find_paths
    entries = os.listdir(current_dir)
OSError: [Errno 13] Permission denied: '/var/lib/graphite/whisper/icinga2/host1'
```
Permissions for host1:
```
ll /var/lib/graphite/whisper/icinga2/host1
total 868
drwx------     4 _graphite _graphite   4096 Nov 10 14:09 ./
drwxr-xr-x 23905 _graphite _graphite 876544 Nov 27 11:27 ../
drwxr-xr-x     3 _graphite _graphite   4096 Nov 10 14:09 host/
drwxr-xr-x     3 _graphite _graphite   4096 Nov  8 11:05 services/
```

Host2 works and returns the data we want. Here's it's permissions:
```
ll /var/lib/graphite/whisper/icinga2/host2
total 868
drwxr-xr-x     4 _graphite _graphite   4096 Oct 29 16:22 ./
drwxr-xr-x 23905 _graphite _graphite 876544 Nov 27 11:27 ../
drwxr-xr-x     4 _graphite _graphite   4096 Nov  8 11:00 host/
drwxr-xr-x     4 _graphite _graphite   4096 Oct 29 14:45 services/
```
Edit: Here's the permissions on the actual wsp's.
```
ll /var/lib/graphite/whisper/icinga2/host1/services/Ambient_Temperature/snmp_temp_check/perfdata/Temp/value.wsp 
-rw-r--r-- 1 _graphite _graphite 1728028 Dec  5 04:21 /var/lib/graphite/whisper/icinga2/host1/services/Ambient_Temperature/snmp_temp_check/perfdata/Temp/value.wsp


ll /var/lib/graphite/whisper/icinga2/host2/services/Ambient_Temperature/snmp_temp_check/perfdata/Temp/value.wsp 
-rw-r--r-- 1 _graphite _graphite 1728028 Dec  5 11:59 /var/lib/graphite/whisper/icinga2/host2/services/Ambient_Temperature/snmp_temp_check/perfdata/Temp/value.wsp
```

**Comment by deniszh** [comment]
Please note permissions for /var/lib/graphite/whisper/icinga2/host1 - it's `drwx------`, so whole dir is not readable for apache process. Fix it with `chmod -R go+rx /var/lib/graphite/whisper/icinga2`

**Comment by cflinspach** [comment]
Thanks, that fixed it.
